services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BACKENDPORT}:${BACKENDPORT}"
    env_file:
      - .env
    networks:
      - app_network
    depends_on:
      - wait-for-db

  wait-for-db:
    image: alpine
    command: >
      sh -c "until nc -z ${POSTGRESQLHOST} ${POSTGRESQLDATABASEPORT}; do echo 'Waiting for DB...'; sleep 2; done;"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
